name: Build and publish orangefox

on:
  push:
    paths:
      - 'recovery.img'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y aria2 python3 cpio wget gh repo
          pip3 install twrpdtgen
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: orangefox-q4q-lazy
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 7583922
          packages: 'build-tools;31.0.0 build-tools;32.0.0 cmake;3.18.1 ndk;23.1.7779620 tools platform-tools platforms;android-31 platforms;android-32'
      - name: Generate tree
        run: |
          cd orangefox-q4q-lazy
          python3 -m twrpdtgen recovery.img
      - name: Prepare OrangeFox
        run: |
          mkdir OrangeFox_sync
          cd OrangeFox_sync
          git clone https://gitlab.com/OrangeFox/sync.git
          cd sync
          ./orangefox_sync.sh --branch 12.1 --path ../fox_12.1
      - name: Copy tree
        run: |
          cp -r orangefox-q4q-lazy/output/* OrangeFox_sync/fox_12.1/device/
      - name: Build recovery
        run: |
          bash -c "cd OrangeFox_sync/fox_12.1;\
          source build/envsetup.sh;\
          export ALLOW_MISSING_DEPENDENCIES=true;\
          export FOX_BUILD_DEVICE=q4q;\
          export LC_ALL="C";\
          lunch twrp_q4q-eng;\
          mka adbd recoveryimage"
      - name: Upload to GitHub releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: OrangeFox_sync/fox_12.1/out/target/product/q4q/OrangeFox-unofficial-q4q.img
          asset_name: orangefox-unofficial-q4q.img
          asset_content_type: application/octet-stream
